Add controllers
3e54Ni7HTXo3Ds/java-shareit pull request #2
Opened 2022-08-24 20:46 UTC by 3e54Ni7HTXo3Ds

2022-08-25 19:13 UTC, alexache requested changes
Комментарии по коду

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.findAll().stream()
Здесь такой же комментарий, как и в другом контроллере - такую конвертацию чаще принято делать в сервисе нежели контроллере

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } else log.error("Некорректный ID: {} ", itemId);
Возможно, что Exception будет более уместен

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemRepository itemRepository;
Для чего делать эти поля публичными?

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getAvailable() == null || item.getName() == null || item.getDescription() == null ||
Такие проверки можно делать как в прошлом проекте навешиванием аннотаций NotBlank/NonNull и т.д.

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!Objects.equals(userId, findById(itemId).getOwner().getId())) {
Что будет, если не существует товара с таким id? NullPointerException?

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@Data
Для чего здесь аннотация @Data?

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
Будет логично иметь такую же комбинацию интерфейса-реализации, как и с ItemService-ItemServiceImpl

2022-08-25 19:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +                .limit(1)
Можно сделать как findAny().isEmpty()

2022-08-26 08:36 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  /**
Окей

2022-08-26 08:37 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@RequestMapping(path = "/items")
Ок

2022-08-26 08:38 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@Data
Ок

2022-08-26 08:40 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private  String name;  //— краткое название;
Ок

2022-08-26 08:42 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +
Ок

2022-08-26 12:03 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private ItemRequest request;/* — если вещь была создана по запросу другого пользователя, то в этом
Ок

2022-08-26 12:07 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        return new ItemDto(
Ок

2022-08-26 12:08 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +        return new UserDto(
Ок

2022-08-27 10:18 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.findAll(userId).stream()
Не очень нравится, что метод в сервисе будет выдавать dto, его не переиспользовать. Но ок.

2022-08-27 10:20 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.search(text).stream()
Ок

2022-08-27 10:22 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.findAll().stream()
Ок

2022-08-27 10:48 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } else log.error("Некорректный ID: {} ", itemId);
Ок

2022-08-27 10:49 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemRepository itemRepository;
Ок

2022-08-27 11:08 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getAvailable() == null || item.getName() == null || item.getDescription() == null ||
Ок, но хотелось бы оставить пока так, надеюсь это не принципиально

2022-08-27 11:15 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!Objects.equals(userId, findById(itemId).getOwner().getId())) {
Ок

2022-08-27 11:16 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@Data
Ок

2022-08-27 11:20 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
Ок

2022-08-27 11:27 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +                .limit(1)
Ок

2022-08-27 19:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getAvailable() == null || item.getName() == null || item.getDescription() == null ||
Не принципиально

2022-08-27 19:58 UTC, alexache approved these changes
Спасибо за исправления!

2022-08-27 19:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  @Data
Еще здесь эта лишняя аннотация осталась, она используется только для каких-то POJO, DTO, но не контроллеров/сервисов

2022-09-02 18:23 UTC, merged