Add bookings
3e54Ni7HTXo3Ds/java-shareit pull request #3
Opened 2022-09-11 15:05 UTC by 3e54Ni7HTXo3Ds

Спринт 14

2022-09-13 18:22 UTC, alexache requested changes

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Item item = itemService.findById(findById(bookingId).get().getItemId());
findById() тоже выхывается много раз, лучше сразу сохранить в переменную

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (Booking.State.ALL.toString().equals(state)) {
Отчего бы не использовать switch-case здесь?

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            item.setName(itemRepository.findById(item.getId()).get().getName());
В идеале такое не должно требоваться, если в букинг объекте уже будет объект айтема

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>          return ItemMapper.toItemDto(itemService.create(userId, itemDto));
Лучше перенести вызов ItemMapper в сервис, чтобы сервис всегда возвращал только Dto объекты

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(r -> Objects.equals(r.getOwner(), userId))
Почему бы сразу не написать такоц метод в репозитории. который будет искать по владельцу и сортировать?

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (itemRepository.findById(itemId).isPresent()) {
Два раза вызывается один и тот же метод поиска, лучше сохранять в переменную

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                ItemResponseDto itemResponseDto = ItemMapper.toItemResponseDto(itemRepository.findById(itemId).get());
Многократный вызов одного и того же метода поиска

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner; //— владелец вещи;
Такой же комментарий, как и для модели бронирования - лучше воспользоваться аннотациями и получить объект юзера сразу здесь

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = findById(itemId);
Птоврный вызов поиска

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Лучше написать в репозитории метод поиска по айди, чем перебирать все в джаве

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    private Long requestor;// — пользователь, создавший запрос;
Тоже можно сделать объектом юзера

2022-09-13 18:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    User findById(Long userId) throws IncorrectParameterException, NotFoundParameterException;
Лучше возвращать из сервиса только UserDto и вызывать маппер внутри сервиса

2022-09-13 19:26 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    String text;// содержимое комментария;
Ок

2022-09-13 19:31 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/dto/CommentResponseDto.java
> +    private UserResponseDto userResponseDto;
Попробовал сделать как здесь https://practicum-students.slack.com/archives/C02TV0U5UKH/p1662803349655099?thread_ts=1662554018.538569&cid=C02TV0U5UKH

2022-09-13 19:32 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    Long id;// уникальный идентификатор комментария;
Ок

2022-09-13 19:42 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!itemService.findById(booking.getItemId()).getAvailable()) {
Ок

2022-09-14 19:25 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "item_id")
Ок

2022-09-14 20:11 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "item_id")
Ок

2022-09-14 20:13 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    private Long requestor;// — пользователь, создавший запрос;
Ок

2022-09-14 20:21 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Item item = itemService.findById(findById(bookingId).get().getItemId());
Ок

2022-09-14 21:29 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (Booking.State.ALL.toString().equals(state)) {
Ок

2022-09-14 21:44 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>          return ItemMapper.toItemDto(itemService.create(userId, itemDto));
Ок

2022-09-14 21:46 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner; //— владелец вещи;
Ок

2022-09-15 18:50 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            item.setName(itemRepository.findById(item.getId()).get().getName());
Ок

2022-09-15 19:06 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    User findById(Long userId) throws IncorrectParameterException, NotFoundParameterException;
Ок

2022-09-15 19:30 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(r -> Objects.equals(r.getOwner(), userId))
Ок

2022-09-15 19:33 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (itemRepository.findById(itemId).isPresent()) {
Ок

2022-09-15 19:35 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                ItemResponseDto itemResponseDto = ItemMapper.toItemResponseDto(itemRepository.findById(itemId).get());
Ок

2022-09-15 19:37 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = findById(itemId);
Ок

2022-09-15 20:08 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Ок

2022-09-16 19:05 UTC, alexache approved these changes

2022-09-16 19:05 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>      Item update(Long itemId, Long userId, ItemDto dto)
Остался еще один метод, который возвращает Item, а не ItemDto

2022-09-18 10:56 UTC, merged