Add item requests
3e54Ni7HTXo3Ds/java-shareit pull request #4
Opened 2022-10-19 04:05 UTC by 3e54Ni7HTXo3Ds

2022-11-09 22:12 UTC, alexache requested changes

2022-11-09 22:12 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertTrue(true, String.valueOf((result.size() == 2)));
Это вообще не очень понятная конструкция,  что с чем тут сравнивается?

2022-11-09 22:12 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +    void search() {
Хорошо бы покрывать как поиск по названию, так и по описанию, отдельными тестам, так и негативный тест

2022-11-09 22:12 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        when(userRepository.findById(item1.getId())).thenReturn(Optional.ofNullable(user1));
Здесь уже запутались item и user

2022-11-09 22:12 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    private final ObjectMapper mapper = new ObjectMapper();
Для чего вручную создавать объект?

2022-11-09 22:12 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +
Нет мока вызова метода delete и нет проверки, что он действительно вызывался

2022-11-09 22:12 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +class BookingControllerTest {
Не хватает теста на BookingRepository, там есть кастомные query

2022-11-09 22:37 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>  @Data
ок

2022-11-09 23:08 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                || !itemRepository.existsById(itemId)
Сейчас это влечет за собой много переделок - учтем на будущее

2022-11-09 23:40 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +@Data
ок

2022-11-10 06:19 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if ((from >= 0) && (size > 0)) {
ок

2022-11-10 08:06 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getAvailable() == null
ок

2022-11-10 08:21 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          if (!itemRepository.existsById(itemId)) {
ок

2022-11-10 08:32 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemRepository.findById(itemId).get();
ок

2022-11-10 11:11 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (itemRequestId > 0) {
ок

2022-11-10 11:37 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>  @Data
ок

2022-11-10 11:38 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        Optional<User> optionalUser = userRepository.findById(any());
ок

2022-11-10 11:39 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertTrue(true, String.valueOf((result.size() == 2)));
3 объекта, в 2 из них есть искомое слово - соответственно 2 должно найти, а 1 не попасть в выборку

2022-11-10 13:28 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +    void search() {
ок

2022-11-10 14:04 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +
добавлен verify, сам метод void

2022-11-10 14:06 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    private final ObjectMapper mapper = new ObjectMapper();
ок

2022-11-10 14:09 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        when(userRepository.findById(item1.getId())).thenReturn(Optional.ofNullable(user1));
ок

2022-11-11 09:32 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void create() throws NotFoundParameterException, IncorrectParameterException {
ок

2023-01-01 21:44 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                item.setItems(ItemMapper.mapToItemResponseDto(itemRepository.findItemByRequestId(item.getId())));
Ок

2023-01-01 21:44 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            for (ItemRequestResponseDto item : list) {
Ок

2023-01-02 19:12 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +class BookingControllerTest {
Ок

2023-01-03 22:42 UTC, alexache approved these changes

2023-01-03 22:42 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/ItemServiceImpl.java
> +public class ItemServiceImpl implements BookingService {
Для чего переименовывать?

2023-01-03 22:42 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertTrue(true, String.valueOf((result.size() == 2)));
assertTrue(true) всегда будет проходить, в чем проверка? Второй аргумент это уже текст сообщения, а не валидация

2023-01-08 20:21 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/practicum/shareit/booking/ItemServiceImpl.java
> +public class ItemServiceImpl implements BookingService {
Ок

2023-01-08 20:21 UTC, 3e54Ni7HTXo3Ds commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertTrue(true, String.valueOf((result.size() == 2)));
Ок

2023-01-08 20:25 UTC, merged