Add docker
3e54Ni7HTXo3Ds/java-shareit pull request #6
Opened 2023-01-15 18:10 UTC by 3e54Ni7HTXo3Ds

2023-01-16 21:49 UTC, alexache requested changes

2023-01-16 21:49 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +//
Закомментированный код лучше удалять

2023-01-16 21:49 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +  //  private Booking.Status status;
Закомментированный код лучше удалять

2023-01-16 21:49 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                          @RequestHeader("X-Sharer-User-Id") Long userId) {
(опционально) Если логгировать, то каждый-каждый метод

2023-01-16 21:49 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemClient.createItem(userId, itemDto);
И здесь логгирование

2023-01-16 21:49 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info("Create booking Dto={}, userId={}", bookingDto, userId);
В BookingServiceImpl осталась валидация, которую нужно перенести в данный метод - 
 `if (end.isBefore(LocalDateTime.now())
                || start.isBefore(LocalDateTime.now())
                || start.isAfter(end)) {
            log.error("Неверное время бронирования: {} ", booking);
            throw new IncorrectParameterException("Неверное время бронирования");
        }`

2023-01-16 21:49 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState state = BookingState.from(stateParam)
OffsetBasedPageRequest еще содержит валидацию from, size, ее тоже стоит перенести в gateway

2023-01-18 12:04 UTC, 3e54Ni7HTXo3Ds commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                          @RequestHeader("X-Sharer-User-Id") Long userId) {
Ок

2023-01-18 12:04 UTC, 3e54Ni7HTXo3Ds commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemClient.createItem(userId, itemDto);
Ок

2023-01-18 13:36 UTC, 3e54Ni7HTXo3Ds commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState state = BookingState.from(stateParam)
Ок

2023-01-18 13:37 UTC, 3e54Ni7HTXo3Ds commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info("Create booking Dto={}, userId={}", bookingDto, userId);
Ок

2023-01-20 10:21 UTC, alexache approved these changes

2023-01-23 10:17 UTC, merged